services:
  - type: web
    name: redis-stream-consumer
    runtime: rust
    repo: https://github.com/wpapper/stablecoin-visualizer
    rootDir: redis-stream-consumer
    buildCommand: cargo build --release
    startCommand: ./target/release/redis-stream-consumer
    envVars:
      - key: REDIS_URL
        sync: false
      - key: REDIS_STREAM_KEY
        value: stablecoin:transactions
      - key: CONSUMER_GROUP
        value: websocket-publisher
      - key: PORT
        value: 8080
      - key: HEALTH_PORT
        value: 8081
    autoDeploy: true
    branch: main