services:
  # Background worker that continuously monitors blockchain
  - type: worker
    name: block-monitor
    runtime: rust
    buildCommand: cargo build --release
    startCommand: ./target/release/block-monitor
    envVars:
      - key: RPC_URL
        sync: false  # Set this in Render dashboard
      - key: PORT
        value: 8080
      - key: HEALTH_PORT
        value: 8081
      - key: RUST_LOG
        value: info
    autoDeploy: true  # Auto-deploy enabled - will deploy on every push to main branch
    
  # Optional: Separate web service for WebSocket connections
  # Uncomment if you want to split WebSocket server from monitor
  # - type: web
  #   name: block-monitor-websocket
  #   runtime: docker
  #   dockerfilePath: ./Dockerfile
  #   dockerContext: ./block-monitor
  #   envVars:
  #     - key: RPC_URL
  #       sync: false
  #     - key: PORT
  #       value: 8080
  #     - key: RUST_LOG
  #       value: info
  #   healthCheckPath: /health