services:
  # Static site for frontend
  - type: web
    name: stablecoin-visualizer-frontend
    runtime: static
    buildCommand: "" # No build needed for static files
    staticPublishPath: ./frontend
    headers:
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
    routes:
      - type: rewrite
        source: /*
        destination: /index.html